# Generated by Django 4.2.16 on 2024-12-05 16:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="whatsapp_number",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="referral_code",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="booking",
            name="booking_reference",
            field=models.CharField(
                db_index=True,
                help_text="Format: YYMMXXXX (Year, Month, Random Digits)",
                max_length=8,
                unique=True,
            ),
        ),
    ]
